# Generated by Django 3.1.2 on 2022-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageproject',
            name='desc',
        ),
        migrations.AddField(
            model_name='manageproject',
            name='describe',
            field=models.CharField(default='', max_length=50, verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='manageproject',
            name='status',
            field=models.BooleanField(default=True, verbose_name='项目状态'),
        ),
        migrations.AddField(
            model_name='manageproject',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='manageproject',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='manageproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manageproject',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='项目名称'),
        ),
    ]
