# Generated by Django 3.1.2 on 2022-07-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20220701_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='模块名称')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='模块描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.manageproject')),
            ],
        ),
    ]
