# Generated by Django 4.0.5 on 2022-07-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0002_alter_managemodule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('url', models.TextField(verbose_name='url')),
                ('req_method', models.CharField(default='', max_length=50, verbose_name='请求方法')),
                ('header_editor', models.TextField(default='', verbose_name='请求头')),
                ('par_type', models.CharField(default='', max_length=50, verbose_name='参数类型')),
                ('parameters', models.TextField(default='', verbose_name='请求参数')),
                ('rep_result', models.TextField(default='', verbose_name='响应结果')),
                ('assert_type', models.TextField(default='', verbose_name='断言类型')),
                ('assert_text', models.TextField(default='', verbose_name='断言文本')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.managemodule')),
            ],
        ),
    ]
